/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.info0502.tp1;

public class App {
    public String getGreeting() {
        return "INFO0502 : Introduction à la programmation répartie ! ";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
